---
main:
  - name: Blog
    identifier: blog
    weight: 1
    url: "/es/blog"
    params:
      icon: '<i class="fas fa-fw fa-terminal"></i>'
  - name: Noticias
    identifier: Noticias
    weight: 2
    url: "/es/news"
    params:
      icon: '<i class="fas fa-fw fa-newspaper"></i>'
  - name: Autores
    identifier: autores
    weight: 3
    url: "/es/authors"
    params:
      icon: '<i class="fas fa-fw fa-heart"></i>'
  - name: Codigo de conducta
    identifier: cdc
    weight: 99
    url: "https://openinfra.dev/legal/code-of-conduct"
    params:
      icon: '<i class="fas fa-fw fa-handshake"></i>'
  - name: Contacto
    identifier: contacto
    weight: 100
    url: "/es/contact"
    params:
      icon: '<i class="fas fa-fw fa-bug"></i>'
---

